### ISSUE TITLE
Rest client error propagation

### ISSUE THREAD

**Issue by alexnadeev** [pip-services3-go/pip-services3-rpc-go#3]
Http service interceptor updates response header with status code (400, 401, 403 and 500) and it does not return any errors. If status code >= 400 then pip-services Rest client creates empty (not nil) error and makes response nil. So, status code does not propagate from service to Http client. The client always receives error with status code 500 with empty message for failed requests.
https://github.com/pip-services3-go/pip-services3-rpc-go/blob/932be3bbc74cec9a143c254c348696916e70ae9b/clients/RestClient.go#L417
It would be great if response status code could propagated from service to client or error with code from response can be handled in Rest client. It could be a better solution as well.

**Comment by levichevdmitry** [comment]
Hi, @alexnadeev! Can you send small example for this case?

**Comment by alexnadeev** [comment]
CLIENT:
import (
	   "reflect"
            data1 "github.com/service-test-go/data"
	   "github.com/pip-services3-go/pip-services3-rpc-go/clients"
)
type TestHttpClientV1 struct {
    *clients.CommandableHttpClient
     TestDataType                     reflect.Type
     TestResponseV1                 reflect.Type
}
func NewTestHttpClientV1() *TestHttpClientV1 {
	c := TestHttpClientV1{}
	c.CommandableHttpClient = clients.NewCommandableHttpClient("v1/tests")
}
func (c *TestHttpClientV1) CreateTest(correlationId string, token *string, test *data1.TestV1) (*data1.TestResponseV1, error) {
	params := cdata.NewAnyValueMapFromTuples(
		"test", test,
	        "token", token,
        )
	response, err := c.CallCommand(c.TestDataType, "create_test", correlationId, params)
	if err != nil {
		return nil, err
	}
       return response, err
}

SERVICE:
import (
	"github.com/pip-services3-go/pip-services3-rpc-go/services"
)

type TestHttpServiceV1 struct {
	*services.CommandableHttpService
}

func (c *TestHttpServiceV1) Register() {
	c.CommandableHttpService.Register()
        c.RegisterInterceptor("create_test", TestHttpInterceptor(token))
}

func TestHttpInterceptor(token string) func(response http.ResponseWriter, request *http.Request, handler http.HandlerFunc) {
	interceptor := func(response http.ResponseWriter, request *http.Request, handler http.HandlerFunc) {
        if token == "" {
                response.WriteHeader(401)
		return
              }
         handler(response, request) 
     } 
     return interceptor
}

**Comment by alexnadeev** [comment]
So, if token was not provided for CommandableHttpClient request (create_test endpoint), service interceptor will write code 401 to the header but code received by client will be 500 with empty error. In case of making direct REST request to the service without token in a payload will have 401 code in response. So, this code does not propagate from service to client.

**Comment by levichevdmitry** [comment]
Hi, @alexnadeev !
Thanks for you example. 
I changed the behavior for decode error algorithm  and add more tests. Now error will correct propagate from service to client, but in client you will always received pointer to Pip.Services ApplicationError struct, you can seen how it works [here](https://github.com/pip-services3-go/pip-services3-rpc-go/blob/7b56e42aea4ac3a89d020affab44624479ad386d/test/clients/DummyClientFixture.go#L75) 
Please, update you dependencies to new version https://github.com/pip-services3-go/pip-services3-rpc-go/releases/tag/v1.4.3
And important, please use Pip.Services ApplicationError and standard helper methods like "SendError" for create response errors.

Good luck!

**Comment by alexnadeev** [comment]
Thanks!
