### ISSUE TITLE
http client retry empties buffer for request

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-rpc-go#4]
https://github.com/pip-services3-go/pip-services3-rpc-go/blob/7b56e42aea4ac3a89d020affab44624479ad386d/clients/RestClient.go#L383

In testing, I was briefly observed the initial call failing for one error and then subsequent calls failing due to the body being empty. I think as coded, when the retry executes, the buffer is emptied on the first call, so subsequent calls will always fail. I just think you'll need to move the code that puts the json string into the request into the while loop.

Let me know if you need some example code. It'll take a bit, but I can make it happen within the week.

**Comment by levichevdmitry** [comment]
Hi @antonio-alexander !
Will great, if you can send me example! 
That will help me to reproduce the error.

**Comment by levichevdmitry** [comment]
I'm updated REST client in new version [v1.4.4](https://github.com/pip-services3-go/pip-services3-rpc-go/releases/tag/v1.4.4-62). Can you test fixes on you code and write to me results?

**Comment by antonio-alexander** [comment]
Fixed! I was able to test by having the http client connect to the grpc port, which would fail due to protocol error, and attempt to retry each time (I expect I could do the same by just choosing a bad port haha). Each time the request at the time of the client.Do() function call had a population ReadCloser(). Thanks!.
