### ISSUE TITLE
SSL crt/key inputs swapped

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-rpc-go#5]
https://github.com/pip-services3-go/pip-services3-rpc-go/blob/a1901d16cbaa526f93c5094e4352acd0017fcc46/services/HttpEndpoint.go#L217

I was attempting to implement SSL with pip-services and found an error here, when I attempt to use it (and uncomment the print line), I get the error:
```
Server stoped: tls: failed to find certificate PEM data in certificate input, but did find a private key; PEM inputs may have been switched
```

__By swapping sslKeyFile and sslCrtFile, I was able to resolve the issue__. In addition, I think it's possible to be able to implement the feedback without there being much issue with a pattern like this:

```go
	chErr := make(chan error, 1)
	if connection.Protocol() == "https" {
		sslKeyFile := credential.GetAsString("ssl_key_file")
		sslCrtFile := credential.GetAsString("ssl_crt_file")

		go func() {
			servErr := c.server.ListenAndServeTLS(sslCrtFile, sslKeyFile)
			if servErr != nil {
				chErr <- servErr
			}
		}()

	} else {
		go func() {
			servErr := c.server.ListenAndServe()
			if servErr != nil {
				chErr <- servErr
			}
		}()
	}
	select {
	case <-time.After(time.Second):
	case err := <-chErr:
		return err
	}
```
In this case, if an error occurs it'll return up the stack and not start the server. In general, most of the errors (at least in Go) you encounter occur REALLY quickly, like within the first couple of seconds, so a slight wait with a select should capture all the relevant errors and maintain the case that when it stops gracefully and outputs an error it's ignored.  You can do some logic to close the channel gracefully, but I don't think it really matters in the grand scheme of things. Something like this:

```go
	chErr := make(chan error, 1)
	defer close(chErr)
	if connection.Protocol() == "https" {
		sslKeyFile := credential.GetAsString("ssl_key_file")
		sslCrtFile := credential.GetAsString("ssl_crt_file")

		go func() {
			servErr := c.server.ListenAndServeTLS(sslCrtFile, sslKeyFile)
			if servErr != nil {
				select {
				default:
					chErr <- err
				case <-chErr:
				}
			}
		}()

	} else {
		go func() {
			servErr := c.server.ListenAndServe()
			if servErr != nil {
				select {
				default:
					chErr <- err
				case <-chErr:
				}
			}
		}()
	}
	select {
	case <-time.After(time.Second):
	case err := <-chErr:
		return err
	}
```

**Comment by levichevdmitry** [comment]
Hello @antonio-alexander!
Thanks for feedback and found issue!
I fixed it and improve error handling as you mention. Try new release please https://github.com/pip-services3-go/pip-services3-rpc-go/releases/tag/v1.5.3 and let me know results.

**Comment by antonio-alexander** [comment]
Thank you for the quick fix! I was able to update my go.mod to use the newest version and didn't encounter an issue; please close at your convenience.
