### ISSUE TITLE
Feature: SSL Implementation is Incomplete

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-rpc-go#6]
I'm in the process of attempting to implement SSL with pip-services with REST (and later GRPC) and I've found that the core functionality I'd planned to use (using just Go and not pip-services) is inaccessible through the pip-services wrapper. This is true for both the client and the server; and it COULD be that my use case doesn't match the original use case you guys built for your rest client/servers, but this seems like an eventual conclusion to desired functionality.

Specifically the things I'm looking to be able to do are:

-  Provide a CA (certificate authority) cert in the event that I'm doing something that's not going on the internet and don't want to pay for a signed CA; this is true for the client and server
- Configure the client authentication level for the server

When I attempted to do the above with your https implementation I was unable to get it to work. And in this case because the user of a browser is desirable using "internal_network" as a configuration parameter isn't an option. I created this repo:  [https://github.com/antonio-alexander/go-blog-https](https://github.com/antonio-alexander/go-blog-https) to try to define some basic use cases and functionality I wanted. Please take a look and let me know if my wants are not in the spirit or scope of your implementation.

> In addition, being able to provide your own CAs allow testing of SSL in a sandbox environment where you can generate the certs and keys dynamically rather than having to have a static cert within the repo

Finally, a big ask I have, is the ability to provide certs in methods that aren't files; for example If I use vault as a secrets store, being able to load certs from vault (as a slice of bytes or a string) would make it easier than having to read from vault, write to disk and then provide that new file to you guys (in terms of order of operation that's also VERY difficult). I think i may be able to use credentials to kind of code around that, but I _imagine_ it'll be difficult.

**Comment by levichevdmitry** [comment]
@antonio-alexander we will try to fix it in near time. I let you know results then.

**Comment by antonio-alexander** [comment]
Awesome. Feel free to tell me to kick rocks if it's not in the spirit of what you guys want to do. Also happy to take a look and provide feedback if you want.

**Comment by levichevdmitry** [comment]
Hello @antonio-alexander we are ready to release new version rpc with proper TLS supporting. Could you help us check it? 
And second one, we improved possibility to develop custom http endpoint with custom certificates sources, so it mean that you could implement your custom mechanism for taking certificates from Vault or some one else place, but by default we trying take it from files described in config. @banalna or me will prepare an example with custom endpoint and share it with you in near time in current discussion.

**Comment by levichevdmitry** [comment]
@antonio-alexander  new release https://github.com/pip-services3-go/pip-services3-rpc-go/releases/tag/v1.6.1
Sample with TLS https://github.com/pip-services3-go/pip-services3-rpc-go/tree/master/example

**Comment by antonio-alexander** [comment]
Awesome, thank you for the quick implementation, I'll try to integrate it into the code I was developing and report back.

**Comment by banalna** [comment]
@antonio-alexander we have added support for setting up custom certificates and CA certificates for clients and services. 

We have added an example with basic implementation and reading certificates from the configuration and an example with a custom endpoint with reading certificates from a custom store.

Please take a look examples: https://github.com/pip-services3-go/pip-services3-rpc-go/tree/master/example

**Comment by antonio-alexander** [comment]
@levichevdmitry  I was able to integrate the latest tag into my code and get it to work. I've got a couple more use cases I want to try out, but I don't expect there to be any issues on your side. Thanks for your quick responses (and changes).
