### ISSUE TITLE
Indirect Panic On Error when using function

### ISSUE THREAD

**Issue by antonio-alexander** [pip-services3-go/pip-services3-rpc-go#7]
https://github.com/pip-services3-go/pip-services3-rpc-go/blob/1ffe0a1873adda7c614d6f87303608bb42e333de/services/HttpResponseSender.go#L26

When Send Error is evoked, the attempt to wrap the error zeros out the status of 500 and causes an indirect panic when you attempt to write a header of 0. I make a strong assumption that you guys were assuming that the underlying type of the err was an ApplicationError and that may be why this wasn't caught.

I was able to avoid the panic by doing this:

```go
func (c *THttpResponseSender) SendError(res http.ResponseWriter, req *http.Request, err error) {
	appErr := cerr.ApplicationError{
		Status:  500,
		Message: err.Error(),
	}
	res.Header().Add("Content-Type", "application/json")
	res.WriteHeader(appErr.Status)
	jsonObj, jsonErr := json.Marshal(appErr)
	if jsonErr == nil {
		io.WriteString(res, (string)(jsonObj))
	}
}
```

But I expect that may be a departure from what you guys wanted to do. I think there are some significant architectural questions this may bring up in terms of how to handle errors. This may help (if you're curious): 
- [https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully]
- [golang_error_handling.md](https://github.com/pip-services3-go/pip-services3-rpc-go/files/12639907/golang_error_handling.md)
- [https://github.com/antonio-alexander/go-bludgeon/blob/main/internal/errors/types.go](https://github.com/antonio-alexander/go-bludgeon/blob/main/internal/errors/types.go)

**Comment by banalna** [comment]
@antonio-alexander we have fixed this bug with error wrapping since version 1.6.5. Thank you!

**Comment by antonio-alexander** [comment]
Thanks, i'll update my version.
